#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-setuptools_git_versioning
Version  : 1.13.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/69/92/dc048ec75e81dca38ff013b48cfb4d9fb54810bf5a56abd4e3c8d5574632/setuptools-git-versioning-1.13.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/69/92/dc048ec75e81dca38ff013b48cfb4d9fb54810bf5a56abd4e3c8d5574632/setuptools-git-versioning-1.13.1.tar.gz
Summary  : Use git repo data for building a version number according PEP-440
Group    : Development/Tools
License  : MIT
Requires: pypi-setuptools_git_versioning-bin = %{version}-%{release}
Requires: pypi-setuptools_git_versioning-python = %{version}-%{release}
Requires: pypi-setuptools_git_versioning-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(packaging)
BuildRequires : pypi(setuptools)

%description
*************************
setuptools-git-versioning
*************************
|status| |PyPI| |PyPI License| |PyPI Python Version|
|ReadTheDocs| |Build| |Coverage| |pre-commit.ci|

%package bin
Summary: bin components for the pypi-setuptools_git_versioning package.
Group: Binaries

%description bin
bin components for the pypi-setuptools_git_versioning package.


%package python
Summary: python components for the pypi-setuptools_git_versioning package.
Group: Default
Requires: pypi-setuptools_git_versioning-python3 = %{version}-%{release}

%description python
python components for the pypi-setuptools_git_versioning package.


%package python3
Summary: python3 components for the pypi-setuptools_git_versioning package.
Group: Default
Requires: python3-core
Provides: pypi(setuptools_git_versioning)
Requires: pypi(packaging)
Requires: pypi(setuptools)

%description python3
python3 components for the pypi-setuptools_git_versioning package.


%prep
%setup -q -n setuptools-git-versioning-1.13.1
cd %{_builddir}/setuptools-git-versioning-1.13.1
pushd ..
cp -a setuptools-git-versioning-1.13.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1669617743
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/setuptools-git-versioning

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
